name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.4.x
      - run: npm ci
      - run: npm run build
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
